layout_spectrum: 0.01937986
typography_spectrum: 0.4408025
color:
  saturation: 0.997775
  lightness: 0.7050352
  brandStrength: 0.7979819
  rhythmicContrast: 0.3891931
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Sophie
